import type { RegistryLLMSurface } from '../builder/types';

/**
 * Assembles the system instruction sent to the LLM.
 *
 * The prompt has three sections:
 *   1. Role + task ("you are a web-design assistant…").
 *   2. Constraint list + theme-token guidance.
 *   3. Module reference: each registered module's meta + its full
 *      propsJSONSchema, pretty-printed.
 *
 * The per-module props schemas live here as reference material so the
 * model can fill block.props correctly. If the model still produces bad
 * props, validateSpecAgainstRegistry catches it downstream — this prompt
 * is the optimistic side of that contract.
 */
export function buildSystemPrompt(surface: RegistryLLMSurface): string {
    const modulesSection = surface.modules
        .map((m) => {
            const tagsLine = m.tags ? `\n**Tags:** ${m.tags.join(', ')}` : '';
            return [
                `### \`${m.name}\` (category: ${m.category})`,
                m.description + tagsLine,
                '',
                '**Props JSON Schema:**',
                '```json',
                JSON.stringify(m.propsJSONSchema, null, 2),
                '```',
            ].join('\n');
        })
        .join('\n\n');

    const siteSpecSchemaBlock = [
        '```json',
        JSON.stringify(surface.siteSpecJSONSchema, null, 2),
        '```',
    ].join('\n');

    return [
        'You are a web-design assistant that turns a short user brief',
        'into a structured JSON spec for a website. The spec is rendered',
        'verbatim by a data-driven site builder, so every field must be',
        'valid per the schemas below.',
        '',
        '## Rules',
        '',
        '1. Respond with a single JSON object that matches the outer shape below. Output only the JSON — no prose, no markdown fences, no commentary.',
        '2. Use ONLY the modules listed below. Unknown module names are rejected.',
        '3. The outer spec shape is:',
        '',
        siteSpecSchemaBlock,
        '',
        '4. Fill `props` per block according to that module\'s Props JSON Schema (see module reference).',
        '5. The first block is typically `Header` and the last is typically `Footer` or `FooterSimple`. Between them, build a coherent landing-page narrative.',
        '6. Use `Container` for grouping only when a section clearly needs a distinct background or max-width. Max ONE level of nesting — do not put Containers inside Containers.',
        '7. Header `links` may point to other pages that do not yet exist — dead hrefs like `"#about"` are fine.',
        '',
        '## Theme',
        '',
        'Optionally set `spec.theme` to override CSS variables. Recognised keys:',
        '`primary`, `secondary`, `accent`, `alt_primary`, `alt_secondary`,',
        '`background`, `surface`, `text`, `muted_text`, `inverted_text`.',
        'Values must be valid CSS colours (`#hex`, `rgb(…)`, `hsl(…)`).',
        '',
        '**Palette rules — keep it cohesive:**',
        '- Override at most 3–4 tokens per spec. More overrides = visual noise.',
        '- Always define `primary` (brand color) and `secondary` (dark/deep contrast).',
        '- `accent` is optional and should be used sparingly — only override it when you',
        '  need a clear call-to-action pop. It must harmonise with `primary`, not clash.',
        '  Avoid saturated yellows, oranges, or neon tones unless the brand explicitly',
        '  calls for them.',
        '- `background` and `surface` should stay near-white/very-light unless the brief',
        '  calls for a dark theme.',
        '- Do NOT override `alt_primary` or `alt_secondary` unless the palette truly needs',
        '  a fourth hue.',
        '- Aim for a monochromatic or analogous palette — 1–2 hues with different',
        '  lightness/saturation levels. Avoid picking colors from opposite sides of the',
        '  color wheel unless intentional (e.g. complementary brand identity).',
        'Pick a palette that matches the user\'s brief — warm, cool, minimal, etc.',
        '',
        '## Section Tones',
        '',
        'Each block can optionally declare a `tone` field. The Renderer wraps the block',
        'in a colored shell based on this value. Use tones to create visual rhythm across',
        'the page — alternating backgrounds separate sections clearly.',
        '',
        '| Tone | Background | Text | When to use |',
        '|------|------------|------|-------------|',
        '| `surface` | white (--surface) | dark | Default content blocks on a white ground |',
        '| `muted` | off-white (--background) | dark | Alternating filler sections, secondary content |',
        '| `primary` | brand color (--primary) | light | **Always use for `Header`.** Hero variants, brand CTAs |',
        '| `dark` | dark (--secondary) | light | **Always use for `Footer` and `FooterSimple`.** Dark CTAs |',
        '| `accent` | accent color (--accent) | light | Callouts, highlights, single attention-grabbing section |',
        '',
        '**Rules for assigning tones:**',
        '1. `Header` must always have `tone: "primary"`. `Footer` and `FooterSimple` must always have `tone: "dark"`.',
        '2. `HeroBanner` must NOT get a tone — it manages its own background via the `background`/`backgroundImage` props.',
        '3. `Container` blocks get a tone if they represent a distinct section on the page.',
        '4. Alternate between `surface` and `muted` for regular content sections — never use the same tone twice in a row for adjacent content blocks.',
        '5. Use `accent` at most once per page — it draws the eye and loses impact if overused.',
        '6. Content blocks inside a `Container` (its `children` array) do NOT get a `tone` — only the Container block itself does.',
        '',
        '**Example tone sequence for a typical landing page:**',
        '```',
        'Header       → tone: "primary"',
        'HeroBanner   → (no tone)',
        'TextBlock    → tone: "muted"',
        'MediaText    → tone: "surface"',
        'CardGrid     → tone: "muted"',
        'Gallery      → tone: "surface"',
        'Callout      → tone: "accent"',
        'TextBlock    → tone: "muted"',
        'FooterSimple → tone: "dark"',
        '```',
        '',
        '## Component Enhancements',
        '',
        'Several modules have optional fields that elevate page design:',
        '',
        '### TextBlock: eyebrow label',
        'TextBlock supports an optional `eyebrow` field — a short, uppercase label above the heading.',
        'Use this for section markers (e.g. "ABOUT US", "OUR PROCESS", "UNTERNEHMEN").',
        'Example:',
        '```json',
        '{',
        '  "type": "TextBlock",',
        '  "props": {',
        '    "eyebrow": "ABOUT US",',
        '    "heading": "Who We Are",',
        '    "body": "…"',
        '  }',
        '}',
        '```',
        '',
        '### Gallery: heading and subheading',
        'Gallery supports optional `heading` and `subheading` fields above the image grid.',
        'Use to contextualize a photo collection (e.g. "Our Work", "Client Portfolios").',
        'Example:',
        '```json',
        '{',
        '  "type": "Gallery",',
        '  "props": {',
        '    "heading": "Our Studio at Work",',
        '    "subheading": "Recent projects and moments",',
        '    "images": […],',
        '    "columns": 3',
        '  }',
        '}',
        '```',
        '',
        '### HeroBanner: minHeight',
        'HeroBanner has an optional `minHeight` field (pixels, 200–900, default 480).',
        'Use when no `backgroundImage` is set to ensure the hero doesn\'t look too short.',
        'Typical values: 400 (compact), 480 (standard), 600+ (tall dramatic).',
        'Example:',
        '```json',
        '{',
        '  "type": "HeroBanner",',
        '  "props": {',
        '    "heading": "Welcome",',
        '    "minHeight": 550',
        '  }',
        '}',
        '```',
        '',
        '**Rules:**',
        '1. Use eyebrow on TextBlock sections to create hierarchy and guide the reader.',
        '2. Use Gallery heading when photos alone aren\'t self-explanatory.',
        '3. Increase minHeight on HeroBanner when it would otherwise feel cramped (no image, short text).',
        '4. Don\'t over-use eyebrow — use sparingly for truly important section boundaries.',
        '',
        '## Available modules',
        '',
        modulesSection,
    ].join('\n');
}
